### ISSUE TITLE
Problem in finding the topological number

### ISSUE THREAD

**Issue by Harry-09** [davidcortesortuno/oommfpy#9]
Hi,
I have a doubt regarding the calculation of topological number, using OOMMFPy I'm able to calculate the from 'omf' file. However, for my dynamics simulation of skyrmion there is also 'odt' file which contain mx, my, mz component.  Is it also possible to calculate from that value or using 'omf' file is way to do that?
It will be of great help if I can know the exact solution for my problem. 

Thanks in Advance!

**Comment by davidcortesortuno** [comment]
Hi, you cannot calculate the topological number from the `odt` file because it contains the average `m` components. You need the space dependent `m` field to calculate the top number. If you look at the so called skyrmion number it is an integral over the derivatives of `m`, you cannot compute that from the averages.

**Comment by Harry-09** [comment]
@davidcortesortuno Thanks for quick response and suggestion.
